create database cryptocurrency_exchanges;
go

CREATE TABLE TB_CURRENCIES(
	ID INT PRIMARY KEY,
	SYMBOL VARCHAR(100),
	[NAME] VARCHAR(255),
	NAME_ID VARCHAR(255)
);

CREATE TABLE TB_EXCHANGES(
	ID INT PRIMARY KEY,
	[NAME] VARCHAR(255),
	[NAME_ID] VARCHAR(255),
	[URL] NVARCHAR(255),
	[VOLUME_USD] DECIMAL(30,5),
	ACTIVE_PAIRS INT,
	COUNTRY VARCHAR(255),
	UPDATE_TIME DATETIME not null DEFAULT GETDATE()
);
GO

CREATE TABLE TB_EXCHANGE_PAIRS(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	ID_EXCHANGE INT,
	BASE VARCHAR(100),
	QUOTE VARCHAR(100),
	[VOLUME] DECIMAL(30,5),
	[PRICE] DECIMAL(30,5),
	[PRICE_USD] DECIMAL(30,5),
	[TIME] BIGINT,
	FOREIGN KEY(ID_EXCHANGE) REFERENCES TB_EXCHANGES(ID) ON DELETE CASCADE
);
GO




--select * from  TB_EXCHANGEs 
--select * from TB_EXCHANGE_PAIRS where base = 'DOGE' and QUOTE = 'BTC'

--select * from TB_CURRENCIES
--drop table TB_EXCHANGEs
--drop table TB_EXCHANGE_PAIRS

